### ISSUE TITLE
Most objects don't drag well

### ISSUE THREAD

**Issue by ChristopherChudzicki** [SketchResponse/sketchresponse#34]
In the most recent version of Sketchresponse (44d15ff1266a057d99eade7b9d337e9dadec75d8) most objects aren't dragging well (everything other than freeform curves, it seems).

1. Open a grading script with points or asymptotes
2. Try dragging a point
 - object gets "stuck"
 - other objects are unable to be selected from now on
3. Curves drag ok initially, but also can't be dragged after a point/asymptote is selected.

**Comment by jmclaus** [comment]
@ChristopherChudzicki 
I did a fresh install from https://github.com/SketchResponse/sketchresponse/commit/44d15ff1266a057d99eade7b9d337e9dadec75d8

Let me detail the steps (I'm using a virtual env), even if it may be obvious, just to make sure something didn't fall through the cracks:

`git clone https://github.com/SketchResponse/sketchresponse.git`
`cd sketchresponse/sketch_tool`
`npm run install`
`npm run build` (needed for local server, see below)
`npm run start`

If I load:

http://localhost:4567/#debug:allPlugins

in a browser, all functions normally.

To run the local server:

`cd ~/sketchresponse`
`virtualenv venv`
`source venv/bin/activate`
`pip install -r requirements.txt`
`python server.py`

If I load:

http://127.0.0.1:5000/complex_grader

in a browser, all functions normally.

If you still have the problem, could you provide your OS/browser? I'm on Linux Mint 18.1 and used latest Chromium and Firefox. Thanks.

**Comment by ChristopherChudzicki** [comment]
@jmclaus Thanks for the detailed instructions! After a fresh install:

- After `npm run start`,  http://localhost:4567/#debug:allPlugins everything is working in Safari and Chrome
- After `python server.py` http://127.0.0.1:5000/complex_grader works in Safari **but not Chrome**. 

In Chrome with the python server, I experience the same dragging issues that Jen and I both had when testing in her office on Tuesday. (I suspect we were both using Chrome at the time.) Again, Safari worked fine.

I'm on macOS 10.12.5. My Safari is 10.1.1 and my Chrome is Version 58.0.3029.110

## Errors
With the Flask server I do get a Python & browser error not present with `npm run start`:
```
Chrome error: favicon.ico Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
Python error: File "/Users/cchudzicki/anaconda/envs/sketchresponse/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named favicon.ico
```

During installation I also got an error about XCODE:
```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

## Installation
I did need to modify your installation instructions slightly, and I did have one error:
1. I had to use `npm install` instead of `npm run install` (`npm ERR! missing script: install`). 
2. My default Python is Anaconda 3.6, so for my virtualenv I used `conda create -n sketchresponse python=2.7` to get a 2.7 instance.

**Comment by jmclaus** [comment]
@ChristopherChudzicki 

- I had to use npm install instead of npm run install (npm ERR! missing script: install).
=> _Sorry for that, I typed hastily, it is the correct command to use as described in the docs.
- `Chrome error: favicon.ico Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
Python error: File "/Users/cchudzicki/anaconda/envs/sketchresponse/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named favicon.ico`
=> We've had this error for a while with the local server, it's unrelated to the current issue. But we should fix it to avoid future confusions.

@ChristopherChudzicki @msegado @jefrench @brian-french 
Thanks for the details Chris. I switched to your Chrome browser version (was using an older version) and can entirely reproduce the behavior you've described. Now for the very bad news. This bug is not related to our recent code modification, it affects ALL versions of the tool (v1.0, 1.1, 1.2) . So what is used in production for all the courses using SketchResponse will BREAK BADLY (ie the tool is basically unusable) with Chrome 58.

Can you please all tell me if these version/configs:

http://sketch-response.surge.sh/sketch-tool/v1/#debug:config1
http://sketch-response.surge.sh/sketch-tool/v1.1/#debug:axesParams

work when you create points and try dragging the LAST point (after it's been created)?

Here's what I gathered so far. Every plugin creates an SVG group node in the DOM and fills it up with shapes ( for example, in the case of the point plugin, a circle SVG node). We get our nasty behavior when the element that is selected is the last one of the group. If you create three points, try dragging pt1 and pt2, things will work perfectly. It also affects line segments for example, dragging the tip of the arrow will freeze movement as it is the last node of the group.

That's why a configuration like this:

http://sketch-response.surge.sh/sketch-tool/v1.1/#debug:allPlugins

will work as the tag text nodes are added at the end of the group.

We just need an extra node after a draggable element if it's the last of the group, it can be anything, even a empty div.

I do not understand this bug yet. Temporary fixes for

v1.0 => add that invisible node where it's needed.
v1.1 and 1.2 => use an empty string tag.

@msegado any ideas? I remove usage of PEP (since pointer events where added recently to Chrome) and it didn't change a thing.

**Comment by msegado** [comment]
@jmclaus From what I was seeing yesterday, it looked like pointercapture was not working; dragging slowly enough that the cursor remained inside an object would work, but dragging quickly so that the cursor moved outside of the object would trigger the bug.

My suspicion is that something in Chrome 58 (or our interaction with it) broke `setPointerCapture`. Haven't been able to find a Chrome bug on it though, but that's probably a good place to start debugging...

A fix would be to attach listeners to the canvas instead of the objects, by the way, but that's annoying.

**Comment by jmclaus** [comment]
@msegado Exactly, a large object like the one produced by the stamp plugin barely displays the bug. I've been going through all the changes implemented in Chrome 57 and 58, I haven't found anything relevant. Attaching the events to the canvas would work, it's how it's implemented in the Mathlets -- I just checked, all is normal with them & Chrome 58. But it would be sad to backtrack to an old technique. Adding a `<g></g>` element at the end of the `render` function works but it feels a bit hacky...

**Comment by msegado** [comment]
@jmclaus Yeah. I'm installing Chrome 59 now and will see if I can reproduce, then try to debug if so.

**Comment by msegado** [comment]
@jmclaus Quick update: still exists in Chrome 59 + I think it might be a zdom bug. Looks like the last element is being destroyed and recreated, which causes a loss of pointer capture. Debugging now.

**Comment by jmclaus** [comment]
@msegado Makes sense and is on par with what I've observed.

**Comment by msegado** [comment]
@jmclaus OK, thankfully it should be an easy fix. It's a bug (sort of) [on line 279 of zdom](https://github.com/SketchResponse/sketchresponse/blob/44d15ff1266a057d99eade7b9d337e9dadec75d8/sketch_tool/lib/util/zdom.js#L279). 

Fix:
----
* L275: `targetEl.__zRoot__.mount(targetEl);` => `targetEl.__zRoot__.mount(targetEl, null);`
* L279: `targetEl.__zRoot__.update(targetEl);` => `targetEl.__zRoot__.update(targetEl, null);`

Explanation:
---

The problem is that this `update()` is called without the second `refEl` argument that `ZNodeCollection#update` expects... this gives `refEl = undefined` which then propagates down the call stack all the way to `ZNode#update`:

```js
  update(refEl) {
    if (this.el.nextSibling === refEl) return;
    this.el.parentNode.insertBefore(this.el, refEl || null);
  }
```

Since browsers use `null`, the condition `this.el.nextSibling === refEl` becomes `null === undefined` for the last element in a group, which triggers `parent.insertBefore(child, null)` unnecessarily.

Now, none of this is new. What I suspect is new is that `parent.insertBefore(child, null)` triggers a loss of pointer capture in the current version of Chrome. I'm not sure if this is due to a change in their handling of pointer events or in that of DOM element moves (it seems to force a move or remove/reinsert* the element, though I don't know if it was doing that before; though note, it's not destroying/creating as I had assumed earlier).

Regardless, the new Chrome behavior is reasonable... we shouldn't expect it to retain pointer capture of an element when we change its position in the DOM.

**Comment by jmclaus** [comment]
@msegado Thanks for the detailed explanation, it just tested it out, it fixes the issue.
